# Generated by Django 5.1.5 on 2026-03-11 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["user", "workspace"], name="workspaces__user_id_5e5274_idx"
            ),
        ),
    ]
