# Generated by Django 5.1.5 on 2026-03-11 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0001_initial"),
        ("workspaces", "0002_membership_workspaces__user_id_5e5274_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["workspace", "-created_at"],
                name="activity_ac_workspa_d5a040_idx",
            ),
        ),
    ]
